Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheDailyPost.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using TheDailyPost.Areas.Identity.Data;

namespace TheDailyPost.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly UserManager<AuthUser> _userManager;
        private readonly PostContext _context;
        //private List<Post> sorted, sortmonth, sortyear;
        private readonly IWebHostEnvironment _hostEnvironment;

        public PostsController(PostContext context, IWebHostEnvironment hostEnvironment, UserManager<AuthUser> userManager)
        {
            _context = context;
            this._userManager = userManager;
            this._hostEnvironment = hostEnvironment;
        }
        [Authorize]
        // GET: Posts
        public async Task<IActionResult> Index()
        {

            var comments = _context.CommentModel.ToList();
       
            ViewBag.Comments = comments;
            return View(await _context.Post.OrderByDescending(x => x.DDMMYY).ToListAsync());
        }
        [Authorize]
        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            var currentUser = _userManager.GetUserName(User);
            var liked_post_id = id;
            var liker_name_status = _context.LikeDetails.Any(ldetails=>ldetails.Liked_Post_id == id && ldetails.Likername==currentUser );
            if (liker_name_status)
            {
                ViewBag.UserStatus = true;
                ViewBag.Icon = "fas";
            }
            else
            {
                ViewBag.UserStatus =false;
                ViewBag.Icon = "far";
            }
            
            return View(post);
        }


        // GET: Details/5/<partial view>AddLike</partial view>
        public IActionResult AddLike()
        {

            return View();
        }
        // POST: Details/5/<partial view>AddLike</partial view
        [HttpPost]
        public IActionResult AddLike(int id, string likername, Post post)
        {
            LikeDetails like = new LikeDetails();
            _context.LikeDetails.Add(new LikeDetails()
            {
               Liked_Post_id = id,
                Likername = likername
            });
            var currentPost = _context.Post.Find(id);
            currentPost.LikeCount = post.LikeCount + 0;
            _context.SaveChanges();

            return RedirectToAction("Details", new { id = id });
        }



        // GET: Details/5/<partial view>AddComment</partial view>
        public IActionResult AddComment()
        {

            return View();
        }
        // POST: Details/5/<partial view>AddComment</partial view
        [HttpPost]
        public IActionResult AddComment(int id, string commentorname,string comment, Post post)
        {
            _context.CommentModel.Add(new CommentModel()
            {
                Commented_Post_id = (int)id,
                Comment = comment,
                Commentorname = commentorname
            });
            var currentPost = _context.Post.Find(id);
            _context.SaveChanges();

            return RedirectToAction("Details", new { id = id });
        }

        public IActionResult AllComments(int ? id)
        {
            _context.Post.ToList();
            return View(_context.CommentModel.OrderByDescending(x => x.Id).Where(cmnted=>cmnted.Commented_Post_id==id).ToList());
        }


        [Authorize]
        public async Task<IActionResult> MyActivity()
        {
            return View(await _context.Post.ToListAsync());
        }
        // GET: Posts/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }



        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date,Month,Year,DDMMYY,Content,Author,AuthorImg,ImageFile,Likers")] Post post)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string filename = Path.GetFileNameWithoutExtension(post.ImageFile.FileName);
                string extension = Path.GetExtension(post.ImageFile.FileName);
                post.ImageName = filename = filename + DateTime.Now.ToString("yymmssff") + extension;
                string path = Path.Combine(wwwRootPath + "/Images/", filename);
                using (var filestream = new FileStream(path, FileMode.Create))
                {
                    await post.ImageFile.CopyToAsync(filestream);
                }
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }
        [Authorize]
        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LikeCount,Id,Title,Date,Month,Year,DDMMYY,Content,Author,ImageFile")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }
        [Authorize]
        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Post.FindAsync(id);
            _context.Post.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        public async Task<IActionResult> Search()
        {
            return View(await _context.Post.ToListAsync());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Search(string parameter)
        {
            var find = _context.Post.Where(a => a.Title.Contains(parameter));
            return View(await find.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> LikeCount(int id, [Bind("Id,LikeCount,Id,Title,Date,Month,Year,DDMMYY,Content,Author,ImageFile")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }
        //User list
        //public IActionResult Usernames()
        //{
        //    return View(_context.Users.ToListAsync());
        //}
        //About Me
        public IActionResult AboutMe()
        {

            return View();
        }

        private bool PostExists(int id)
        {
            return _context.Post.Any(e => e.Id == id);
        }
    }
}

Views/Shared/AddComment.cshtml
@model Post
@using TheDailyPost.Models
@using Microsoft.AspNetCore.Identity
@using TheDailyPost.Areas.Identity.Data

@inject SignInManager<AuthUser> SignInManager
@inject UserManager<AuthUser> UserManager
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddComment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="id" type="hidden" asp-for="Id" />
            @*<div class="form-group">
            <label asp-for="Commented_Post_id" class="control-label"></label>
            <input asp-for="Commented_Post_id" class="form-control"  />
            <span asp-validation-for="Commented_Post_id" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input hidden name="commentorname" class="form-control" value="@UserManager.GetUserName(User).Substring(0,UserManager.GetUserName(User).IndexOf("@"))" />
                <textarea name="comment" required class="form-control"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Comment" class="btn" style="background: #2772c2;color:white;" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/AddLike.cshtml
@model Post
@using TheDailyPost.Models
@using Microsoft.AspNetCore.Identity
@using TheDailyPost.Areas.Identity.Data

@inject SignInManager<AuthUser> SignInManager
@inject UserManager<AuthUser> UserManager


<script>
    function AddLike() {
        var currentcount = document.getElementById("Like").value;
        document.getElementById("Like").value = Number(currentcount) + Number(1);
    }

</script>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLike">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="id" type="hidden" asp-for="Id" />

            <div class="form-group">
                <input hidden name="likername"  value="@UserManager.GetUserName(User)" class="form-control" />
            </div>
            <div class="form-group">
                <label hidden asp-for="LikeCount" class="control-label"></label>
                <button style="border-radius:100%" type="submit" disabled="@ViewBag.UserStatus" onclick="AddLike()" value="" class="btn"><i style="color:red;" class="@ViewBag.Icon fa-heart"></i></button><b><input readonly style="border:none;width:50px;font-size:large;" id="Like" asp-for="LikeCount" /> </b>
                <br /><br />
                
                
                <span asp-validation-for="LikeCount" class="text-danger"></span>
            </div>
            
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/AllComments.cshtml
@model IEnumerable<CommentModel>


<br />
<br /> 
    <div class="container">
        <div class="card container">
            @foreach (var item in Model)
            {
                if (item == null)
                {
                    <p>No Comments so far...</p>
                }
                else
                {
                    <h6>@item.Commentorname</h6>
                    <p>@item.Comment</p>
                }
            }
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        i {
            color: black;
        }
        .support{
        }

    </style>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Daily Post</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Icons CDN link -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

</head>

<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background: #2772c2">
            <div class="container">
                <h4 style="font-family:cursive;color:white;">The Daily Post</h4>
                <a class="btn" href="https://rzp.io/l/74Donatexq6f" target="_blank" style="float: right; color: white; border-color:white;">Support Us!</a>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            <br /><br />
            @RenderBody()
        </main>
    </div>
    <nav class="navbar fixed-bottom navbar-dark" style="background: white; ">
        <div class="container-fluid">
            <a class="nav-link" asp-area="" asp-controller="Posts" asp-action="Index"><i class="fas fa-home fa-1x"></i></a>
            <a class="nav-link" asp-area="Identity" asp-page="/Account/Logout"><i class="fas fa-power-off fa-1x"></i></a>
            <a class="nav-link" asp-area="" asp-controller="Posts" asp-action="Create"><i class="fas fa-plus-circle fa-1x"></i></a>
            <a class="nav-link" asp-area="" asp-controller="Posts" asp-action="Search"><i class="fas fa-search fa-1x"></i></a>
            <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"><i class="fas fa-user-circle fa-1x"></i></a>
        </div>

    </nav>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
<footer>
    <div class="container">
        <div class="text-center center-block">
            <p class="txt-railway">
                &copy; @DateTime.Today.ToString("yyyy") ALL RIGHTS RESERVED <a asp-action="AboutMe"><B style="color: #2772c2 "> Ajay Karumathil</B></a> 
                | <small>DEVELOPED BY <a asp-action="AboutMe"><B style="color: #2772c2 ">AJAY KARUMATHIL</B></a> </small>
            </p>
        </div>
<br /><br /><br />
    </div>
</footer>
</body>
</html>